version: "3"

services:
  server:
    container_name: "SERVER-Temet-Cards-App"
    build: "."
    volumes:
      - "./:/node-app/"
      - "./node_modules:/node-app/node_modules"
    depends_on:
      - db
    ports:
      - "9000:9000"

  db:
    image: "mongo"
    container_name: "DB-Temet-Cards-App"
    ports:
      - "27017:27017"
    volumes:
      - "./data/db:/data/db"

volumes:
  node_modules:
